### ISSUE TITLE
MapDataDao: callback on request complete

### ISSUE THREAD

**Issue by rostopira** [westnordost/osmapi#10]
Is there any methods to listen for map data request complete? I need to display data only after everything is loaded (very small part of data, few mb)

**Comment by westnordost** [comment]
The methods of the DAOs are synchronous. So

```
mapDao.getMap(boundingBox, myMapDataHandler);
everythingIsLoaded();
```

**Comment by rostopira** [comment]
@westnordost that's awesome, I can use async-await. Thanks =)
