### ISSUE TITLE
testByClosedAfter fails on timezone different from Europe/Berlin

### ISSUE THREAD

**Issue by kruchinin-pavel** [westnordost/osmapi#12]
I've tried it on my Moscow's PC and found test issue.
Fix is attached.

Test fails: 
![test_fails](https://user-images.githubusercontent.com/5062078/31667732-f1f1ac66-b358-11e7-994f-1684b872768c.jpg)

Fix:
[testByClosedAfter.patch.zip](https://github.com/westnordost/osmapi/files/1391232/testByClosedAfter.patch.zip)

**Comment by westnordost** [comment]
The test case always assumes to be run in UTC+1, so it is the test case that must be fixed, not the code.

**Comment by kruchinin-pavel** [comment]
Okay. TestCase fix attached. Please have a look.
[testByClosedAfter.patch.zip](https://github.com/westnordost/osmapi/files/1393529/testByClosedAfter.patch.zip)

**Comment by westnordost** [comment]
Hm? I already fixed it myself and pushed it to the repos

On 18 October 2017 07:37:23 CEST, Pavel Kruchinin <notifications@github.com> wrote:
>Okay. TestCase fix attached. Please have a look.
>[testByClosedAfter.patch.zip](https://github.com/westnordost/osmapi/files/1393529/testByClosedAfter.patch.zip)
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/osmapi/issues/12#issuecomment-337465393

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
