### ISSUE TITLE
Add suggestion for jdk version upgrade or adding LE certs.

### ISSUE THREAD

**Issue by bitsondatadev** [westnordost/osmapi#15]
Seems like oracle wasn't compatible with let's encrypt certs until [Java 7 >= 7u111 and Java 8 >= 8u101](https://stackoverflow.com/questions/34110426/does-java-support-lets-encrypt-certificates). I was on jdk 8_92 and I got:

> sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

It would be nice to specify in the README or Wiki to verify either you have added lets encrypt certs to your ${JAVA_HOME}/jre/lib/security/cacerts file or that you have the most recent jdk version which will contain support for lets encrypt ca certs.

Thanks for writing this lib. Very helpful!

**Comment by westnordost** [comment]
I am sorry, I don't understand what this has to do with this lib. It is an open source lib that is delivered as source code from maven central. With what java version you conpile your code is a matter of configuration in your software, is it not?

**Comment by westnordost** [comment]
Is openstreetmap.org a LE cert?

**Comment by bitsondatadev** [comment]
Yes, they use an LE cert. You don't technically have to update your jdk but that was a quick and simple way to take care of adding le certs. They could also just add the le cert to their truststore.

**Comment by bitsondatadev** [comment]
I guess I shouldn't call it a requirement. You could call it a possible solution to this issue if anyone runs into this issue.

**Comment by westnordost** [comment]
Okay, I added a short paragraph to the readme, thank you, Brian!

**Comment by bitsondatadev** [comment]
No problem. Thank you for this lib! It's saving me some hassle :).
