### ISSUE TITLE
NullPointerException if node does not have version attribute

### ISSUE THREAD

**Issue by jonathanjhosue** [westnordost/osmapi#20]
I think the error is in line 113 in mapDataParser. some times when it is a custom map or it is not a reviewed version, the nodes (for example) may not have version attribute. Version is a int variable so it is failing there when it returns null.

version = getIntAttribute("version");

**Comment by westnordost** [comment]
Yes correct, the version attribute is currently non-optional. In any calls to the OSM Api, it is included.

What is this custom map you are speaking of?

**Comment by jonathanjhosue** [comment]
Maybe I am wrong, I was using a not uploaded  map from JOSM and probably the error is there since it does not set a version for just created (not confirmed by openstreetmap) nodes and ways, so it could be different there. By custom maps I meant osm maps files for other reasons (test, games, etc..) out of openstreetmap repository.

**Comment by westnordost** [comment]
Hmm, what's your use case?

Am 24. April 2019 09:41:05 MESZ schrieb jonathanjhosue <notifications@github.com>:
>Maybe I am wrong, I was using a not uploaded  map from JOSM and
>probably the error is there since it does not set a version for just
>created (not confirmed by openstreetmap) nodes and ways, so it could be
>different there. By custom maps I meant osm maps files for other
>reasons (test, games, etc..) out of openstreetmap repository.

**Comment by westnordost** [comment]
Closing because no feedback
