### ISSUE TITLE
Update comments

### ISSUE THREAD

**Issue by vmichalak** [westnordost/osmapi#22]
Hello

On the comment below the link is no more ok
https://github.com/westnordost/osmapi/blob/f23aa7a0257417dd4eb93cb0e677b10c2f8f509b/libs/core/src/main/java/de/westnordost/osmapi/user/Permission.java#L4

Is it possible to update it with this link : https://github.com/openstreetmap/openstreetmap-website/blob/master/db/structure.sql#L1108

**Comment by westnordost** [comment]
Ok corrected it, thanks
