### ISSUE TITLE
Wiki permissions

### ISSUE THREAD

**Issue by sebkur** [westnordost/osmapi#31]
Hi,
I'd like to fix broken links to the source files in https://github.com/westnordost/osmapi/wiki/Combine-With-Data-Processing-Libraries however I can't seem to edit the wiki page. Do you mind enabling that somehow or giving me (temporary) permission to edit the wiki?

**Comment by westnordost** [comment]
I forgot that this wiki site even exists. I think I should just put that into the repos as an .md document.

**Comment by westnordost** [comment]
It is now here: https://github.com/westnordost/osmapi/blob/master/Combine_With_Data_Processing_Libraries.md

**Comment by sebkur** [comment]
ah, ok, great!
