### ISSUE TITLE
Deploy the artifact to maven central

### ISSUE THREAD

**Issue by szbaalint** [westnordost/osmapi#5]
Please deploy version 1.1 to maven central repository:
https://mvnrepository.com/artifact/de.westnordost/osmapi

**Comment by westnordost** [comment]
That is odd. I could have bet that I did this right after I pushed your fix.

Oh well, it is done now. Thank you for the reminder, must have made something wrong during the deploy.
http://repo1.maven.org/maven2/de/westnordost/osmapi/1.1/
