### ISSUE TITLE
Indent exception

### ISSUE THREAD

**Issue by vnhjdh** [westnordost/osmapi#8]
mapDataDao.updateMap(...) fails with:

java.lang.IllegalStateException: unsupported feature http://xmlpull.org/v1/doc/features.html#indent-output

running the code on glassfish.

**Comment by westnordost** [comment]
Can you supply the full stack trace?

Am 19. Mai 2017 12:27:30 MESZ schrieb Jonas Donovan Hansen <notifications@github.com>:
>mapDataDao.updateMap(...) fails with:
>
>java.lang.IllegalStateException: unsupported feature
>http://xmlpull.org/v1/doc/features.html#indent-output
>
>running the code on glassfish.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/osmapi/issues/8

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
Nevermind, found it.

The Xmlpullparser implementation you are using does not support the indentation feature. Do you exclude and replace the kxml2 maven dependency with something else?

Am 19. Mai 2017 12:27:30 MESZ schrieb Jonas Donovan Hansen <notifications@github.com>:
>mapDataDao.updateMap(...) fails with:
>
>java.lang.IllegalStateException: unsupported feature
>http://xmlpull.org/v1/doc/features.html#indent-output
>
>running the code on glassfish.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/osmapi/issues/8

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by vnhjdh** [comment]
I don't think I do. Here my dependencies list:

compile 'javax.inject:javax.inject:1'
compile 'org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.0.Final'
compile 'org.hibernate:hibernate-core:5.2.9.Final'
compile 'org.hibernate:hibernate-spatial:5.2.9.Final'
compile 'org.postgresql:postgresql:42.0.0'
compile 'net.postgis:postgis-jdbc:2.2.1'
compile 'org.springframework.data:spring-data-jpa:1.11.1.RELEASE'
compile 'org.springframework:spring-core:4.3.7.RELEASE'
compile 'org.springframework:spring-orm:4.3.7.RELEASE'
compile 'org.springframework:spring-jdbc:4.3.7.RELEASE'
compile 'org.springframework:spring-aop:4.3.7.RELEASE'	
compile 'org.springframework:spring-beans:4.3.7.RELEASE'
compile 'org.springframework:spring-tx:4.3.7.RELEASE'
compile 'org.springframework:spring-expression:4.3.7.RELEASE'
compile 'org.springframework:spring-context:4.3.7.RELEASE'
compile 'org.springframework:spring-context-support:4.3.7.RELEASE'
compile 'org.springframework:spring-webmvc:4.3.7.RELEASE'
compile 'org.springframework.security:spring-security-web:4.2.2.RELEASE'
compile 'org.springframework.security:spring-security-web:4.2.2.RELEASE'
compile 'org.springframework.security:spring-security-config:4.2.2.RELEASE'  
compile 'commons-fileupload:commons-fileupload:1.3.2'
compile 'org.springframework.hateoas:spring-hateoas:0.23.0.RELEASE'
compile 'javax.cache:cache-api:1.0.0'
compile 'net.sf.ehcache:ehcache:2.10.3'
compile 'org.apache.commons:commons-dbcp2:2.1.1'
compile 'cglib:cglib:3.2.5'
compile 'org.slf4j:slf4j-api:1.7.25'
compile 'com.jayway.jsonpath:json-path:2.2.0'
compile 'com.mangofactory:swagger-springmvc:1.0.2'
compile 'commons-collections:commons-collections:3.2.2'
compile 'org.apache.commons:commons-lang3:3.5'
compile 'com.fasterxml.jackson.core:jackson-core:2.8.8'
compile 'com.fasterxml.jackson.core:jackson-databind:2.8.8'
compile 'com.fasterxml.jackson.core:jackson-annotations:2.8.8'
compile 'com.squareup.retrofit2:retrofit:2.2.0'
compile 'com.squareup.retrofit2:adapter-rxjava:2.2.0'
compile 'com.squareup.retrofit2:converter-gson:2.2.0'
compile 'com.squareup.okhttp3:okhttp:3.7.0'
compile 'com.squareup.okhttp3:logging-interceptor:3.7.0'
compile 'com.squareup.okio:okio:1.12.0'
compile 'io.reactivex:rxjava:1.2.10'
compile 'com.googlecode.libphonenumber:libphonenumber:8.4.0'
compile 'com.norconex.commons:norconex-commons-lang:1.12.3'
compile 'org.imgscalr:imgscalr-lib:4.2'
runtime 'com.h2database:h2:1.4.192'
runtime 'org.slf4j:slf4j-log4j12:1.7.25'
compile 'javax.servlet:javax.servlet-api:3.1.0'
provided 'javax.servlet:javax.servlet-api:3.1.0'
compile 'com.amazonaws:aws-java-sdk-s3'
compile 'de.westnordost:osmapi:1.6'
testCompile 'com.jayway.jsonpath:json-path-assert:2.2.0'
testCompile 'org.springframework:spring-test:4.3.7.RELEASE'
testCompile 'junit:junit:4.12'
testCompile "org.mockito:mockito-all:1.10.19"

**Comment by westnordost** [comment]
Removed that feature and deployed. Should show up in maven central soon.

https://oss.sonatype.org/content/repositories/releases/de/westnordost/osmapi/1.7/
